currentBuild.displayName = "#${BUILD_NUMBER}"
currentBuild.description = "Create new testing app environment"

pipeline {
    agent {
        label 'provisioner'
    }
    options {
        timestamps()
    }
    parameters {
        choice(
            name: 'ENVIRONMENT', 
            choices: ['dev', 'uat'], 
            description: 'Choose environment'
        )
        text(
            name: "ENV_NAME",
            description: "Unique name for the environment you want to create. It'll be used to create unique resources and could be used as part of DNS entries."
        )
        string(
            name: "PARAMETER_STORE_NAMESPACE",
            description: "Base SSM parameter store namespace where configurations are stored."
        )
    }
    environment {
        AWS_ACCESS_KEY_ID = credentials('jenkins-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('jenkins-secret-key')
        AWS_DEFAULT_REGION = 'us-west-2'
    }
    stages {
        stage('Validate extra params') {
            input {
                message "Need some extra info"
                ok "Send"
                parameters {
                    string(name: "OWNER", description: "Resource owner")
                    string(name: "TEAM", description: "Resource team")
                }
            }
            steps {
                echo "Owner: ${OWNER}"
                echo "Team: ${TEAM}"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}

